### ISSUE TITLE
[Feature] HVPA Roadmap

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/hvpa-controller#30]
**Feature (What you would like to be added):**
Summarise the roadmap for HVPA with links to the corresponding issues.

**Motivation (Why is this needed?):**
A central place to collect the roadmap as well as the progress.

**Approach/Hint to the implement solution (optional):**

- [ ] The goal of HVPA is to re-use the upstream components [HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) and [VPA](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler) as much as possible for scaling components horizontally and vertically respectively.
  - [ ] HPA for recommendation and scaling horizontally.
    - [X] `Auto` update policy for HPA updates with `0` or `100` weight for HPA.
    - [ ] Values between `0` and `100` for HPA weight.
    - [ ] `Off` and `ScaleUp` update policy for HPA updates.
  - [X] VPA for recommendation for scaling vertically.
    - [ ] Any value between `0` and `100` for HPA weight.
    - [X] `Off`, `Auto` and `ScaleUp` update policy for VPA updates.
- [ ] Where there are gaps in using HPA and VPA simultaneously to scale a given component, introduce functionality to fill those gaps.
  - [X] HPA and VPA are recommended to be mixed only in case HPA is used for custom/external metrics as mentioned [here](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#limitations-of-beta-version). But in some scenarios it might make sense to use them both even for CPU and memory (e.g. `kube-apiserver` or ingress etc.)
  - [X] VPA updates the pods directly (via webhooks) which may confuse HPA (especially, when used for the same scaling metrics) as it may not see the changes in the upstream `targetRefs`.
- [ ] Where there is functionality missing in either HPA or VPA, introduce them to provide more flexibility during horizontal and vertical scaling. Especially, for the components that experience disruption during scaling.
  - [ ] Weight-based scaling horizontally and vertically simultaneously.
    - [X] Only values 0` or `100` as weight for HPA.
    - [X] Any value between `0` to `100` as weight for VPA.
    - [ ] Any value between `0` to `100` as weight for HPA.
  - [X] Support for configurable (at the resource level) threshold levels to trigger VPA (and possibly HPA) updates to minimize unnecessary scaling of components. Especially, if scaling is disruptive.
  - [X] Support for configurable (at the resource level) stabilisation window in all the four directions (up/down/out/in) to stabilize scaling of components. Especially, if scaling is disruptive.
  - [ ] Support for configurable maintenance window for scaling (especially, scaling in/down) for components that do not scale well smoothly (mainly, `etcd`, but to a lesser extent `kube-apiserver` as well for `WATCH` requests). This could be as an alternative or complementary to the stabilisation window mentioned above.
  - [ ] Support for flexible update policy for all four scaling directions (Off/Auto/ScaleUp). ScaleUp would only apply scale up and not scale down (vertically or horizontally). This is again from the perspective of components which experience disruption while scaling (mainly, `etcd`, but to a lesser extent `kube-apiserver` as well for `WATCH` requests). For such components, a `ScaleUp` update policy will ensure that the component can scale up (with some disruption) automatically to meet the workload requirement but not scale down to avoid unnecessary disruption. This would mean over-provisioning for workloads that experience a short upsurge.
  - [ ] Custom resource support for VPA updates.
     - [ ] At the beginning, this would be with some well-defined annotations to describe which part of the CRD to update the resource requests.
     - [ ] But eventually, we can think of proposing a `Resource` subresource (per container) along the lines of `Scale` subresource.
