### ISSUE TITLE
☂️ Control Plane Stabilization

### ISSUE THREAD

**Issue by vlerenc** [gardener/hvpa-controller#79]
**Feature (What you would like to be added):**
We have seen various control plane issues like:
- [ ] One `OOMKilled` pod triggers new VPA recommendations that are then rolled out to all replicas, recreating all of them and thereby terminating all connections and putting stress on the system to reinitialise (e.g. taking down ETCD)
- [ ] VPA fails to deal properly with spikes and recommends requests below current usage
- [ ] Once a large cluster control plane fails, it cannot recover by itself anymore as the components restart in a vicious cycle

**Motivation (Why is this needed?):**
While this is actually a Gardener topic, it is being implemented actually here:
- Stable control plane, even if spikes or load tests stress it
- Support for large clusters of 500 and more nodes

**Comment by vasu1124** [comment]
Please plan for a public blog article that desribes this unique feature of Gardener on a high-level, such that it can be used to attract interest and establish thought leadership (internal as well as external)
